### PR TITLE
Display py.test results as they come in

### LINKED ISSUE #13: Display test results as they come in

### LINKED ISSUE #50: Use py.test's API to run tests
At the moment, we parse the JUnitXml output, which has the advantage that we can use the same code for py.test and nose. However, the JUnitXml output does not have all the information we need. In particular, this issue is a prerequisite for #12, #13 and #47.

### PR DESCRIPTION
**Pull request by jitseniesen**
The goal of this pull request is to give the user continuous feedback on the test run, instead of waiting till the end before displaying any results. I find it curiously satisfying to see the count of successful test go up and up. :wink: This required a change in the design: instead of parsing the JUnitXml (which is generated after the test run), the plugin now interacts with py.test's API.

This turned out to be more work than I expected, but it is almost done now. Hopefully the new design will pay back in the future.

To do:
- [x] Check Python 2 compatibility
- [x] Eliminate py.test warnings in tests
- [x] Eliminate code duplication in `RunnerBase.start()` and `PytestRunner.start()`
- [x] Move JUnitXml parsing from `RunnerBase` to `NoseRunner`

Fixes #13 
Fixes #50

### CODE REVIEW

**Comment by jitseniesen** [comment]
After:
realtime-after

Before:
realtime-before

**Comment by goanpeca** [comment]
This is very nice work @jitseniesen, I like it :-)

**Comment by goanpeca** [comment]
@jitseniesen maybe we should change the name from `Kill` to `Stop` ?

**Comment by ccordoba12** [comment]
Great addition @jitseniesen!

**Comment by jitseniesen** [comment]
> @jitseniesen maybe we should change the name from `Kill` to `Stop` ?

Good idea --> #92

**Pull request merged**
