### PR TITLE
Load and save configuration for tests

### LINKED ISSUE #43: Save selected test framework
The test framework (nose, py.test, unittest) should be saved between invocations of Spyder so that the user does not have to specify the test framework again after quitting Spyder. This should probably be done per project.

I guess this requires changes to Spyder ...

### PR DESCRIPTION
**Pull request by jitseniesen**
The configuration is saved in the project preferences (because it is probably specific to a particular project), so that the user does not have to specify the testing framework again in subsequent sessions. If no project is opened, the configuration is not saved. Fixes #43.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This looks really interesting! We should preferences for Projects so users don't need to edit the project associated ini file by hand, right?

**Comment by jitseniesen** [comment]
Users do not need to edit the `.ini` file by hand. It is linked to a dialog window. It works as follows:
1. When a project is opened, the configuration is loaded from the project's `unittest.ini` file. If the file does not exist, it is created with an empty configuration.
2. If the user runs the tests and no configuration is set, the configuration dialog window is showed (see picture below) allowing the user to specify the configuration.
3. The user can change the configuration by clicking an item in the plugin's option menu.
4. Whenever the configuration is set or changed, it is saved in the project's `unittest.ini` file (if a project is opened).

Configuration dialog window:
screenshot_20161119_110807

Items 2 and 3 are already implemented; this PR implements 1 and 4.

There is no tab for the unittest plugin preferences in the Spyder preferences. This is partially because I don't know how to add plugin project preferences to the Spyder preferences. It does not help that quite a bit of the project preferences code seems not to be used (I guess it is work in progress). However, even if it can be done, I don't know whether it makes a better user experience.

**Comment by ccordoba12** [comment]
Thanks for the explanation. I think what you've done is a very good approach.

**Comment by jitseniesen** [comment]
I opened #89 to address the decrease in coverage.

**Pull request merged**
