### PR TITLE
PR: Show undock action

### LINKED ISSUE #83: Changes for compatibility with new undocking behavior of Spyder
As discussed in Spyder [PR #3824](https://github.com/spyder-ide/spyder/pull/3824)

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #83 

Preview:

undock

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, does this change make `spyder-unittest` incompatible with Spyder 3?

**Comment by dalthviz** [comment]
@ccordoba12 yep, since in Spyder 3.x the base plugin class doesn't have the `self.options_button` and `self.options_menu` attributes. Should I prevent this?

**Comment by jitseniesen** [comment]
@dalthviz wrote:

> yep, since in Spyder 3.x the base plugin class doesn't have the `self.options_button` and `self.options_menu` attributes. Should I prevent this?

If possible, yes.

At the moment the plugin is compatible with both Spyder 3 and 4, and I'd like to keep that. If that proves to be too difficult, then I'll merge PRs that break compatibility with Spyder 3 only when Spyder 4 is at least close to release.

Where is the new plugin behaviour documented?

I saw you also changed some stuff with actions. Is that necessary, and if so, why?

**Comment by dalthviz** [comment]
Hi @jitseniesen about the documentation, you could check Spyder PR [#3824](https://github.com/spyder-ide/spyder/pull/3824), although you have made a good point, I think that we have to do a proper documentation about this.

About the change in the actions, it's in order to retrieve the actions when calling `get_plugin_actions` since there is a need to clear the menu and add again the actions when changing from the docked version to the window version of a plugin.

Also, I will try to make this changes compatible between versions of Spyder then (with this and the other plugins) :+1:

**Pull request merged**
