### PR TITLE
Move tests to a standalone location

### PR DESCRIPTION
**Pull request by ghisvail**
Given that the tests are excluded from installation and their execution is completely standalone, it makes more sense to move them out of the package directory into a separate `tests` directory, like the majority of other Python projects do.

### CODE REVIEW

**Comment by goanpeca** [comment]
we decided against this as we want est code to be avaiñable to users and close to the code thay gets tested

**Comment by ghisvail** [comment]
> we want est code to be avaiñable to users

What do you mean by "available"? Please be more explicit.

> close to the code thay gets tested

What is the advantage? The test suite is standalone and the name of the individual test files is explicit enough to easily relate to which individual component is covered.

**Comment by goanpeca** [comment]
@ghisvail we had this conversation for spyder a long time ago and we decided this was the way we wanted it.

**Comment by ccordoba12** [comment]
@ghisvail, I agree with @goanpeca: we want tests to be part of the distributed package and not placed in a different location.

> like the majority of other Python projects do.

Not for Pandas: https://github.com/pandas-dev/pandas/tree/master/pandas/tests

or IPython: https://github.com/ipython/ipython/tree/master/IPython/core/tests

> Given that the tests are excluded from installation ...

So the solution is simple: include our tests as part of the package :-)

**Comment by ghisvail** [comment]
> We want the code to be part of the shipped package

Until #56 (requested by myself) that was not the case...

>  in a way users can explore it by looking at tests close to the file that may have produced a problem

One might argue it is more straightforward to look for test code under an immediate folder called `tests`, rather than browsing the Python package looking for sub-folders.

> Not for Pandas [...] or IPython

Nor `spyder` itself, indeed. We are talking different size of codebase here, however. Having the tests nested within such a small codebase looks really overkill.

> So the solution is simple: include our tests as part of the package :-)

Go ahead.

This PR was formulated as a suggestion anyway. Feel free to reject.

**Comment by ccordoba12** [comment]
@jitseniesen, what do you have to say about this?

**Comment by jitseniesen** [comment]
I don't see any strong arguments either way. Whether it makes more sense to have the tests separately seems rather subjective. So I'll keep things as they are.

Thanks ghisvail for the suggestion.

**Comment by ghisvail** [comment]
> Whether it makes more sense to have the tests separately seems rather subjective.

There are recommended practices in the `pytest` [documentation](http://doc.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules).

The guidelines are in favour of the layout I propose (first bullet point), unless the decision is to *install* the tests alongside the package. This is currently not the case due to the exclusion pattern applied to the `find_package` call in `setup.py`.

Of course you are free to choose to deviate from these guidelines, but keep in mind that downstream tools, such as the Debian packaging and CI tools, defaults to support these recommended practices in order to reduce the corresponding package maintenance effort.

**Comment by bilderbuchi** [comment]
>  This is currently not the case due to the exclusion pattern applied to the find_package call in setup.py.

Considering that @goanpeca and @ccordoba12 say above that they "want tests to be part of the distributed package", this seems to be a bug.

**Comment by ccordoba12** [comment]
@jitseniesen, I agree with @bilderbuchi. We should provide tests as part of the package so that they can be run independently (e.g. by Debian).

**Comment by jitseniesen** [comment]
Tests are part of the .tar.gz package that you download from PyPI (which is what Debian uses, as I understand it). Tests are not installed and thus not included in the binary wheel or the anaconda package because I think these are mostly used by people who won't be running tests. If you feel tests should be installed, please open an issue.

**Comment by ccordoba12** [comment]
@ghisvail?

**Comment by ghisvail** [comment]
Never mind. The PR was rejected, I'll move on to something else.

**Pull request closed without merging**
