### PR TITLE
Add config dialog to allow user to choose py.test or nose

### LINKED ISSUE #3: Add an option to choose the test suite
pytest and nostesets are harcoded and need a code edit to be switched. There should be a config page to chose the one wanted.

### PR DESCRIPTION
**Pull request by jitseniesen**
* Add config dialog with radio buttons for py.test and nose, and combo box for choosing working directory
* Add button to unittest widget for configuring tests
* "Run tests" button and menu item now display config dialog if tests are not yet configured
* Remove combo box for choosing directory and date label from widget and put remaining buttons on one line

Fixes #3 and #18

### CODE REVIEW

**Comment by goanpeca** [comment]
@jitseniesen could you add screenshot?

**Comment by jitseniesen** [comment]
This is a screenshot of the unittest plugin pane after running some tests:
screenshot_20161119_110406

The configuration dialog:
screenshot_20161119_110807

**Comment by ccordoba12** [comment]
This is really nice! Keep up the good work @jitseniesen!

**Comment by jitseniesen** [comment]
The Linux CI on Circle fails with the message 
```
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```
It looks at first sight to be an incompatibility between libicui and (Qt or PyQt or qtpy). However, when I switched to Travis to do the Linux CI it seems to work.

@goanpeca Something for you to take a look at when you have time.

**Comment by goanpeca** [comment]
>Something for you to take a look at when you have time.

Will do.

Regarding your screen shot, we should have a convention of having the cog icon be on the right so that it is standard among all plugins. We could even add some helpers as part of the plugin API so that if config opitons are added, the menu will appear on the same location for all plugins.

**Comment by jitseniesen** [comment]
> Regarding your screen shot, we should have a convention of having the cog icon be on the right so that it is standard among all plugins

Here is a mock-up of an alternative UI. The Start button will turn into a Stop button while the tests are running. All other buttons (Config, Show log, Collapse all, Expand all) are under the cogwheels icon. This leaves some room where we can summarize the result of the test. 

Do you think this is better?

test

**Comment by goanpeca** [comment]
@jitseniesen yes! I definitely like it better as it is less stuff and more concise and in line with the rest :-)

For the configuration dialog a combobox might be better? I think is better thinking ahead in terms of language agnostic stuff.

**Comment by jitseniesen** [comment]
> For the configuration dialog a combobox might be better? I think is better thinking ahead in terms of language agnostic stuff.

Yes, a combobox is indeed better. I'm adding this suggestion to #4 because I want to merge this PR; it's already big enough.

**Pull request merged**
